Config 				  = {}
Config.cooldown		  = 1700

Config.Weapons = {
	"WEAPON_STUNGUN",
	"weapon_nailgun",
	"weapon_TEC9BRP",
	"weapon_m1911BRP",
	"weapon_HK45BRP",
	"weapon_PT92",
	"weapon_FNP",
	"weapon_broomBRP",
	"weapon_cleaverBRP",
	"weapon_dildoBRP",
	"weapon_fireaxeBRP",
	"weapon_shovelBRP",
	"weapon_guitarBRP",
	"weapon_glockBRP",
	"weapon_scarBRP",
	"weapon_sigBRP",
	"weapon_na2BRP",
	"weapon_g36BRP",
	"weapon_m8",
	"weapon_m110BRP",
	"weapon_remington870BRP",
	"weapon_sigmpx",
	"weapon_makarovBRP",
	"weapon_msr",
	"weapon_scarlBRP",
	"weapon_tar21",
	"weapon_vectorBRP",
	"weapon_makarov",
	"weapon_mp40",
	"weapon_augBRP",
	"weapon_mp7BRP",
	"weapon_ppshBRP",
	"weapon_MOSINBRP",
	"weapon_WINCHESTER12BRP",
	"weapon_akmBRP",
	"weapon_ak74BRP",
	"weapon_vesperBRP",
	"weapon_m4a1BRP",
	"weapon_re6BRP",
	"weapon_ump45BRP"
}